//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockBase.Dapps.NeverForget.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TwitterTokens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TwitterTokens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlockBase.Dapps.NeverForget.Services.Resources.TwitterTokens", typeof(TwitterTokens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1351921561155072002-aVv7lXhYNn8DKWMuTISpQzG1It1slU.
        /// </summary>
        internal static string ACCESS_TOKEN {
            get {
                return ResourceManager.GetString("ACCESS_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M6DPxMJyzgzT2oci5Z5c1T5Y70ZwtInYtwvTdp1GU9fiq.
        /// </summary>
        internal static string ACCESS_TOKEN_SECRET {
            get {
                return ResourceManager.GetString("ACCESS_TOKEN_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9qQx8bvfeJcPqdJl2DRgcsmcU.
        /// </summary>
        internal static string CONSUMER_KEY {
            get {
                return ResourceManager.GetString("CONSUMER_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QD9iYlaRvHyz0795Ba2R8Mv02PV62F7zqzPubhn48VclIt78zv.
        /// </summary>
        internal static string CONSUMER_SECRET {
            get {
                return ResourceManager.GetString("CONSUMER_SECRET", resourceCulture);
            }
        }
    }
}
